\mainmatter

# Elementos básicos de un fractal geométrico

Son necesarios conceptos preliminares ...

## Conjuntos (Reconocer conjuntos como una forma - conexidad - Mobius y Klein)

Una forma es una colección de puntos en el espacio 0D, 1D, 2D y 3D.
Las formas 0D y 1D son el punto y la línea respectivamente. Cuyas características son: Posición, en el caso del punto. Posición, dirección (el ángulo de inclinación con respecto a la horizontal en sentido anti horario), longitud y centro de masa en el caso de las líneas.
Las formas 2D y 3D delimitada por una frontera (línea-formas 2d o superficie-formas 3d). Cuya características son: Posición, dirección, área o volumen, eje, centro de masa. Existen dos tipos de superficie: Orientables (poseen dos caras) por ejemplo el toro, la esfera, etc. No orientables por ejemplo la Botella de Klein y la Cinta Mobius.

### Elementos primarios de la forma

1. Punto.
2. Línea (rectas(vertical-horizontal-diagonal-quebrada), curvas y mixtas)
3. Plano o superficie: https://www.geogebra.org/m/bzAhy4Yv
4. Volumen: https://www.geogebra.org/classic/cff7ma3b

### Clasificación de las formas

1. Según su origen
    * Naturales: Creadas por la naturaleza.
    * Artificiales: Creadas por el ser humano.
2. Según su estructura
    * Formas orgánicas: tienen un perfil y una superficie interior irregulares. En muchos casos proceden de la naturaleza (una piedra, un árbol, el dibujo del ala de una mariposa).
    * Formas geométricas: son las formas que se crean a partir de un orden y proceso matemático o geométrico, un panal de abejas (vértices, aristas y planos).
3. Según la relación con el espacio
    * Formas cerradas: Encierran región .
    * Formas abiertas: No encierran una región.
4. Según su configuración espacial
    * Formas planas: son aquellas que tienen dos dimensiones.
    * Formas tridimensionales: son formas que tienen tres dimensiones
5. Según la complejidad de su estructura
    * Formas simples: son las que están compuestas por pocos elementos.
    * Formas complejas: son formas compuestas por varios elementos.

### Centro de masa y ejes de las formas

El centro de masas representa el punto en el que suponemos que se concentra toda la masa del sistema para su estudio. El eje es cualquier recta que pasa por su centro de masa. El eje que contiene al mayor segmento de intersección con el objeto es el eje principal


### Algebra de formas (conjuntos)
www
[@leithold1990calculus]

*fracción impropia* \index{fracción impropia}


## Operaciones con conjuntos
<!--
Son las siguientes

1. Distanciamiento. Dos formas mantienen una relación de distanciamiento cuando existe una separación entre ellas $_1\cap _2=\emptyset$.
2. Toque. Existe relación de toque cuando las formas están en contacto $_1\cap _2={}$ (conjunto unitario).
3. Superposición. Existe superposición cuando una forma tapa a otra y de esta solo vemos la parte que no está tapada $_1\cup (_2-_1)$.
4. Unión. Dos formas tienen una relación de unión cuando se funde y los contornos de las dos formas se complementan $_2\cup _1$.
5. Intersección. Existe relación de intersección entre dos formas cuando surge una nueva forma fruto de la zona común entre ellas. Es decir, ambas formas comparten una superficie del plano y esta genera una nueva forma $_2\cap _1$.
6. Sustracción. La relación de sustracción se produce cuando una forma no aparece representada, pero resta el espacio común a la otra creando un vacío $_2-_1$.
7. Penetración. Existe relación de penetración entre formas cuando se crea un vacío en el espacio común entre ellas $_2\: \Delta\: _1$.
2. Transparencia. En una relación de transparencia entre formas, ambas formas comparten un espacio en común, pero se aprecia el contorno de ambas. Podemos entenderlo como una superposición de una forma translúcida sobre otra ($_2\cup _1)\cup (_1\cap _2$).
-->

### Relación entre operaciones entre formas y los fractales

La relación radica en que estas relaciones deben utilizarse en las iteraciones de las formas en la estructura de un fractal.



## Coordenadas cartesianas 2d y 3d (Plano y sólidos) - representación de puntos, lineas y planos (Geogebra)

### Coordenadas cartesianas 2D (plano)
<!--
El sistema en sí es un sistema bidimensional, que se denomina plano cartesiano. El punto de intersección de las rectas, por definición, se considera como el punto cero de las rectas y se conoce como origen de las coordenadas. Al eje horizontal o de las abscisas se le asigna los números reales de las equis ("x"); y al eje vertical o de las ordenadas se le asignan los números reales de las ye ("y").

Al cortarse las dos rectas, dividen al plano en cuatro regiones o zonas, que se conocen con el nombre de cuadrantes:

* Primer cuadrante "I": Región superior derecha
* Segundo cuadrante "II": Región superior izquierda
* Tercer cuadrante "III": Región inferior izquierda
* Cuarto cuadrante "IV": Región inferior derecha

Tres ejemplos de coordenadas asignadas a tres puntos diferentes (verde, rojo y azul), sus proyecciones ortogonales sobre los ejes constituyen sus coordenadas cartesianas y el origen de coordenadas (0,0) en magenta.
-->
### Coordenadas cartesianas 3D (espacio)
<!--
Las coordenadas cartesianas 3D especifican una ubicación precisa mediante el uso de tres valores de coordenadas X,Y y Z. Especificar valores de coordenadas cartesianas 3D (X,Y,Z) es similar a especificar valores de coordenadas 2D (X,Y). Además de indicar los valores x e y, se debe especificar también el valor z utilizando el formato siguiente: (x,y,z).

En la figura siguiente, la coordenada 3,2,5 indica un punto situado a tres unidades a lo largo del eje X positivo, a 2 unidades a lo largo del eje Y positivo, y a 5 unidades del eje Z positivo
-->
### Coordenadas cartesianas absolutas y relativas

Como en el caso de las coordenadas bidimensionales, se pueden introducir valores de coordenada absoluta, basados en el origen, o valores de coordenada relativa, basados en el último punto introducido.


### Ejercicios
<!--
* Realice un bosquejo 2D-cartesiano
* Realice un bosquejo 3D-cartesiano (Ejemplo: diapositiva anterior)
-->

## Transformaciones elementales sobre formas 2D y 3D
<!--
::: {.definition #transformaciones name="Transformaciones"}
Es un conjunto de procesos que se realiza a alguna forma en particular sin modificar la forma.
:::



### Traslacion

En geometría, a la traslación, el movimiento de cada punto a una distancia constante en una dirección dada.


### Rotación

Rotación es la acción que ejerce un cuerpo para dar un giro, vuelta o rodar alrededor de su propio eje.

### Homotecia

Escala o proporción, razón de proporción- centro de homotecia

### Reflexión

Cada punto se refleja a través de un eje de simetría en el plano y el espacio el eje simetría recibe el nombre plano especular (simetría especular)
-->


## Transformaciones topológicas (Taza - donuts -- Zbrush metamorfosis)
<!--
De manera informal, la topología se ocupa de aquellas propiedades de las figuras que permanecen invariantes, cuando dichas figuras son plegadas, dilatadas, contraídas o deformadas, de modo que no aparezcan nuevos puntos, o se hagan coincidir puntos diferentes. La transformación permitida presupone, en otras palabras, que hay una correspondencia biunívoca entre los puntos de la figura original y los de la transformada, y que la deformación hace corresponder puntos próximos a puntos próximos. Esta última propiedad se llama continuidad, y lo que se requiere es que la transformación y su inversa sean ambas continuas: así, trabajarnos con homeomorfismos.

::: {.definition #transformacionestopo name="Transformaciones topológicas"}
Consiste en doblar, estirar, encoger, retorcer, etc., los objetos, pero siempre que se haga sin romper ni separar lo que estaba unido, ni pegar lo que estaba separado. Por ejemplo, un triángulo es topológicamente lo mismo que una circunferencia, ya que
podemos transformar uno en otra de forma continua, sin romper ni pegar. Pero una circunferencia no es lo mismo que un segmento, ya que habría que partirla (o pegarla) por algún punto.

Esta es la razón de que se la llame la "geometría de la página de goma", porque es como si estuviéramos estudiando geometría sobre un papel de goma que pudiera contraerse, estirarse, etc.
:::

La esfera se trasforma topológicamente en un elefante. Pero el toro no puede transformase en una esfera
-->
### Propiedades preservadas bajo transformaciones topológicas
<!--
Algunas propiedades se conservan bajo transformaciones topológicas y otras no. La propiedad de un círculo de ser una curva cerrada simple es una propiedad que se conserva bajo una transformación topológica arbitraria. Es una propiedad topológica. La superficie de una esfera tiene las siguientes dos propiedades que se conservan bajo una transformación topológica arbitraria.
1. La superficie está cerrada. No hay bordes en él (como con un cuadrado).
2. Toda curva simple cerrada en su superficie representa una disección de la misma en este sentido: si hacemos un corte a lo largo de la curva, la superficie se separa en dos partes inconexas.
-->
### Género de una superficie
<!--
El género de una superficie es su tipo topológico. Las superficies del mismo género son topológicamente equivalentes entre sí. Las superficies de diferentes géneros no son topológicamente equivalentes. ¿Qué característica de una superficie nos permite determinar su género. La característica es esta: el mayor número de curvas cerradas simples que no se cruzan que se pueden dibujar en la superficie sin separarla (es decir, hacer que la superficie se separe en partes desconectadas cuando se hacen cortes a lo largo de las curvas).

::: {.example name="Transformación topológicas de la $N$ esfera"}
El género de una esfera es 0 ya que no se pueden dibujar tales curvas en su superficie sin separarla. El género de un toro es 1, y no más de uno tales curvas se pueden dibujar en su superficie sin separarlo. Considere ahora la rosquilla de doble orificio que se muestra en la Fig. 5. Tiene un género de 2 ya que dos, pero no más, de tales curvas se pueden dibujar en su superficie sin separarla. De manera similar, una rosquilla con tres orificios tiene un género de 3 desde tres, y no más, tales curvas se pueden dibujar en su superficie sin separarla, y en general, una rosquilla con orificios p tiene un género de p desde p (y no más) tales curvas se pueden dibujar en su superficie sin separarla.
:::
-->
### Superficies de una sola cara o superficies no orientables  
<!--
El espacio en dos dominios, uno interior y otro exterior, constituyendo la superficie el límite común entre los dos dominios. Este hecho está conectado con otro. Ahora demostraremos algunas superficies que tienen un solo lado. La primera que exponemos es la cinta de Móbius se construye tomando una larga banda rectangular de papel y pegando los dos extremos después de darle media vuelta como se muestra en la Fig. 8. Una extensión es la botella de Klein.

https://solitaryroad.com/c775.html
https://en.wikipedia.org/wiki/Topology

-->
## Recursividad o iteración de transformaciones 2D y 3D (Secuencias)



## Principios de la composición y las transformaciones (Relación-fractal)         

## Sustentación de trabajos (\emph{Objeto fractal, geométrico digital o manual})
